-- migrate:up transaction:false

CREATE ROLE "Role.Owner" WITH
	LOGIN
	NOSUPERUSER
	CREATEDB
	NOCREATEROLE
	NOINHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD NULL;

COMMENT ON ROLE "Role.Owner" IS 'Właściciel baz Panel.EmotoAgh';


CREATE ROLE "Role.CRUD" WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD NULL;
COMMENT ON ROLE "Role.CRUD" IS 'Rola posiadająca crud na schematy';


CREATE ROLE "Role.Dev" WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD NULL;
COMMENT ON ROLE "Role.Dev" IS 'Daje dostęp do deweloperskich baz aplikacji';


CREATE ROLE "Role.Production" WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD NULL;

GRANT "Role.Dev", "Role.CRUD" TO "Role.Production";
COMMENT ON ROLE "Role.Production" IS 'Daje dostęp do produkcyjnej bazy aplikacji';


-- migrate:down transaction:false

DROP ROLE IF EXISTS "Role.Production";
DROP ROLE IF EXISTS "Role.Dev";
DROP ROLE IF EXISTS "Role.CRUD";
DROP ROLE IF EXISTS "Role.Owner";
